export const sustainableReact = {
    title: "Sustainable React: The Green Code Revolution of 2026 🌿",
    description: "In 2026, efficiency is survival. A definitive 5,000-word guide on writing 'Green Code' that reduces carbon footprints, optimizes CPU cycles, and aligns with the new era of Digital Sustainability.",
    slug: "sustainable-react",
    type: "static",
    author: "Eco-Engineering Lead",
    createdAt: new Date().toISOString(),
    readTime: "45 min read",
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?q=80&w=2670&auto=format&fit=crop",
    tags: ["React 19", "Sustainability", "Green Tech", "Performance", "Architecture"],
    keywords: ["Green Code", "Digital Decarbonization", "Sustainable Web Design", "React Compiler", "Server-Side Thinning", "Carbon Calculator", "Eco-friendly", "OLED Optimization"],
    toc: [
        { id: "math-of-green-code", label: "01. The Math of Green Code" },
        { id: "hidden-cost-js", label: "02. The Hidden Cost of JS" },
        { id: "react-compiler-efficiency", label: "03. React Compiler & Energy" },
        { id: "server-side-thinning", label: "04. Server-Side Thinning" },
        { id: "image-font-optimization", label: "05. Heavy Assets: Images & Fonts" },
        { id: "dark-mode-oled", label: "06. OLED & Dark Mode" },
        { id: "carbon-metrics", label: "07. Metrics: LCP vs Carbon" },
        { id: "green-hosting", label: "08. Green Hosting Strategy" },
        { id: "carbon-calculator-hook", label: "09. Build: Carbon Calculator" },
        { id: "virality", label: "10. Share The Movement" }
    ],
    content: `
    <div class="space-y-16 font-sans text-gray-800 dark:text-gray-200">
        
        <!-- 01. The Math -->
        <section id="math-of-green-code" class="scroll-mt-32">
            <div class="border-l-8 border-emerald-600 bg-emerald-50 dark:bg-emerald-900/10 pl-8 py-8 mb-12 rounded-r-2xl shadow-sm">
                <h1 class="text-4xl md:text-5xl font-black text-gray-900 dark:text-white leading-tight mb-6">
                    Every KB is a Puff of Smoke.
                </h1>
                <p class="text-xl md:text-2xl text-emerald-800 dark:text-emerald-200 font-light leading-relaxed">
                    We used to optimize for speed (Core Web Vitals). Now, we optimize for survival. 
                    <br/><br/>
                    The internet emits more carbon than the airline industry. Every unnecessary re-render in your React app heats up a CPU, which draws power from a grid that is likely burning coal. 
                    <strong>"Green Engineering"</strong> isn't just a buzzword—it is the default architecture constraint of 2026.
                </p>
            </div>
            
            <div class="prose prose-xl max-w-none text-gray-700 dark:text-gray-300 leading-8">
                <p>
                   When you ship a 5MB bundle to a user on a 4G connection in a region with a "dirty" energy grid (like coal-heavy grids), you are directly responsible for the emissions generated by that data transfer and the subsequent CPU crunching required to parse it. 
                </p>
                <p>
                    <strong>The Equation:</strong> <br/>
                    <code>Data Transfer (GB) x Energy Intensity (kWh/GB) x Carbon Intensity (gCO2/kWh) = Footprint</code>.
                    <br/><br/>
                    As React developers, we control the <strong>CPU Cycles</strong> (how hard the device works) and the <strong>Data Transfer</strong> (how much energy the network uses). By reducing bundle sizes and preventing wasted computations, we directly lower the carbon emissions of our digital products.
                </p>
            </div>
        </section>

        <!-- 02. Hidden Cost of JS -->
        <section id="hidden-cost-js" class="scroll-mt-32">
             <h2 class="text-3xl md:text-4xl font-extrabold text-gray-900 dark:text-white mb-8 flex items-center gap-4 border-b pb-4 dark:border-gray-800">
                <span class="text-emerald-600 dark:text-emerald-500">02.</span>
                The Hidden Cost of JavaScript
            </h2>
            <div class="prose prose-lg max-w-none text-gray-700 dark:text-gray-300 mb-8">
                <p>
                    JavaScript is the most expensive resource on the web. Images cost bandwidth, but JavaScript costs <strong>bandwidth + parsing + compilation + execution</strong>.
                </p>
                <p>
                    A 200KB JPEG is decoded instantly by the GPU. A 200KB JS bundle locks the main thread for 1.5s on a Moto G4, burning battery and heating up the device. 
                    <br/>
                    <strong>Green Code Rule #1:</strong> The greenest code is the code you never write.
                </p>
            </div>
            <div class="bg-yellow-50 dark:bg-yellow-900/10 border-l-4 border-yellow-500 p-6 rounded-r-lg">
                <p class="text-yellow-800 dark:text-yellow-200 font-medium">
                    <strong>Fact:</strong> A single line of unoptimized <code>useEffect</code> causing an infinite loop can drain 1% of a mobile user's battery in minutes.
                </p>
            </div>
        </section>

        <!-- 03. React Compiler -->
        <section id="react-compiler-efficiency" class="scroll-mt-32">
             <h2 class="text-3xl md:text-4xl font-extrabold text-gray-900 dark:text-white mb-8 flex items-center gap-4 border-b pb-4 dark:border-gray-800">
                <span class="text-emerald-600 dark:text-emerald-500">03.</span>
                The React Compiler: An Energy Saver
            </h2>
            <p class="text-lg text-gray-700 dark:text-gray-300 mb-8">
                The React Compiler (React 19+) doesn't just make apps faster; it makes them cooler (literally). 
                Manual Memoization (<code>useMemo</code>, <code>useCallback</code>) was error-prone. The Compiler auto-memoizes, ensuring that your component <strong>never</strong> re-renders unless data actually changes.
            </p>
            
            <div class="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
                <div class="bg-red-50 dark:bg-red-900/10 p-6 rounded-xl border border-red-100 dark:border-red-900/30">
                    <h4 class="font-bold text-red-700 dark:text-red-300 mb-4">Legacy React (The Gas Guzzler)</h4>
                    <p class="text-sm text-gray-600 dark:text-gray-400">Parent re-renders -> All Children re-render. Thousands of wasted CPU cycles checking standard diffs. High battery drain on mobile devices.</p>
                </div>
                 <div class="bg-emerald-50 dark:bg-emerald-900/10 p-6 rounded-xl border border-emerald-100 dark:border-emerald-900/30">
                    <h4 class="font-bold text-emerald-700 dark:text-emerald-300 mb-4">React 19 (Electric Vehicle)</h4>
                    <p class="text-sm text-gray-600 dark:text-gray-400">Compiler "freezes" non-dependent branches. CPU stays idle. Battery life preserved. Carbon saved. It is equivalent to regenerative braking for code.</p>
                </div>
            </div>
        </section>

        <!-- 04. Server-Side Thinning -->
        <section id="server-side-thinning" class="scroll-mt-32">
             <h2 class="text-3xl md:text-4xl font-extrabold text-gray-900 dark:text-white mb-8 flex items-center gap-4 border-b pb-4 dark:border-gray-800">
                <span class="text-emerald-600 dark:text-emerald-500">04.</span>
                Server-Side Thinning & Edge
            </h2>
            <div class="prose prose-lg max-w-none text-gray-700 dark:text-gray-300">
                <p>
                    <strong>Principle:</strong> Move computation to where the energy is most efficient.
                    <br/>
                    A user's old smartphone is energy-inefficient. A hyperscale "Green Region" data center (like AWS us-west-2 Oregon, powered by Hydro, or Google's Finland region) is highly efficient. 
                </p>
                <p>
                    By using <strong>React Server Components (RSC)</strong>, we "thin out" the client bundle. We render complex logic on the green server and send only the HTML result to the client. This is <strong>Server-Side Thinning</strong>.
                </p>
            </div>
            
            <div class="mockup-code bg-gray-900 text-gray-100 p-6 rounded-xl overflow-x-auto shadow-xl text-sm border border-emerald-900/30 my-8">
                <div class="text-emerald-400 mb-2">// Server Component (Runs in Green Data Center)</div>
                <pre><code>import { format } from 'date-fns'; // Heavy Lib
import { marked } from 'marked'; // Heavy Lib

export default async function BlogPost({ id }) {
  // DB Fetch (High Efficiency)
  const post = await db.post.find(id);
  
  // Computation (Done on Server)
  const html = marked.parse(post.content);
  const date = format(post.date, 'MM/dd/yyyy');

  // Client receives ONLY pure HTML.
  // Zero KB of JS for libraries sent to browser.
  return (
    &lt;article&gt;
      &lt;h1&gt;{post.title} -- {date}&lt;/h1&gt;
      &lt;div dangerouslySetInnerHTML={{ __html: html }} /&gt;
    &lt;/article&gt;
  );
}</code></pre>
            </div>
        </section>

        <!-- 05. Assets -->
        <section id="image-font-optimization" class="scroll-mt-32">
             <h2 class="text-3xl md:text-4xl font-extrabold text-gray-900 dark:text-white mb-8 flex items-center gap-4 border-b pb-4 dark:border-gray-800">
                <span class="text-emerald-600 dark:text-emerald-500">05.</span>
                Heavy Assets: Images & Fonts
            </h2>
             <p class="text-lg text-gray-700 dark:text-gray-300 mb-6">
                Media is typically 80% of total page weight.
            </p>
            <ul class="space-y-4">
                <li class="p-4 bg-gray-100 dark:bg-slate-900 rounded-lg">
                    <strong class="block text-xl mb-1">1. AVIF > WebP > JPEG</strong>
                    <p class="text-sm text-gray-600">AVIF offers 20% better compression than WebP. Use modern formats with fallbacks.</p>
                </li>
                <li class="p-4 bg-gray-100 dark:bg-slate-900 rounded-lg">
                    <strong class="block text-xl mb-1">2. Font Subsetting</strong>
                    <p class="text-sm text-gray-600">Don't load the entire 'Inter' font (200KB). Use unicode-range to only load Latin characters if that's all you use. This drops font files to ~20KB.</p>
                </li>
                <li class="p-4 bg-gray-100 dark:bg-slate-900 rounded-lg">
                    <strong class="block text-xl mb-1">3. Lazy Loading Below fold</strong>
                    <p class="text-sm text-gray-600"><code>loading="lazy"</code> on images is mandatory. Also, <code>decoding="async"</code> prevents UI jank.</p>
                </li>
            </ul>
        </section>

        <!-- 06. OLED & Dark Mode -->
        <section id="dark-mode-oled" class="scroll-mt-32">
             <h2 class="text-3xl md:text-4xl font-extrabold text-gray-900 dark:text-white mb-8 flex items-center gap-4 border-b pb-4 dark:border-gray-800">
                <span class="text-emerald-600 dark:text-emerald-500">06.</span>
                OLED Optimization
            </h2>
             <p class="text-lg text-gray-700 dark:text-gray-300 mb-6">
                Most modern devices (Phones, MacBooks) use OLED screens. On an OLED screen, a black pixel is literally <strong>OFF</strong>. It consumes zero energy. A white pixel consumes maximum energy.
            </p>
            <div class="p-8 bg-black rounded-3xl border border-gray-800 shadow-2xl mb-8">
                 <h3 className="text-white text-2xl font-bold mb-4">Energy Consumption by Color</h3>
                 <div className="space-y-4">
                     <div className="flex items-center gap-4">
                         <div className="w-12 h-12 bg-white rounded shadow-inner"></div>
                         <div className="flex-1">
                             <div className="h-4 bg-gray-800 rounded-full w-full overflow-hidden">
                                 <div className="h-full bg-red-500 w-[100%]"></div>
                             </div>
                             <div className="text-xs text-gray-400 mt-1 uppercase font-bold">White (#FFFFFF) - 100% Energy</div>
                         </div>
                     </div>
                     <div className="flex items-center gap-4">
                         <div className="w-12 h-12 bg-gray-500 rounded shadow-inner"></div>
                         <div className="flex-1">
                             <div className="h-4 bg-gray-800 rounded-full w-full overflow-hidden">
                                 <div className="h-full bg-yellow-500 w-[60%]"></div>
                             </div>
                             <div className="text-xs text-gray-400 mt-1 uppercase font-bold">Gray (#808080) - 60% Energy</div>
                         </div>
                     </div>
                     <div className="flex items-center gap-4">
                         <div className="w-12 h-12 bg-black border border-gray-800 rounded shadow-inner"></div>
                         <div className="flex-1">
                             <div className="h-4 bg-gray-800 rounded-full w-full overflow-hidden">
                                 <div className="h-full bg-emerald-500 w-[0.1%]"></div>
                             </div>
                             <div className="text-xs text-gray-400 mt-1 uppercase font-bold">True Black (#000000) - ~0% Energy</div>
                         </div>
                     </div>
                 </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400">
                <strong>Actionable Tip:</strong> Default your app to Dark Mode. Use #000000 or #050505 instead of lighter grays for backgrounds.
            </p>
        </section>

        <!-- 07. Metrics -->
        <section id="carbon-metrics" class="scroll-mt-32">
             <h2 class="text-3xl md:text-4xl font-extrabold text-gray-900 dark:text-white mb-8 flex items-center gap-4 border-b pb-4 dark:border-gray-800">
                <span class="text-emerald-600 dark:text-emerald-500">07.</span>
                Carbon Metrics in DevTools
            </h2>
            <p class="text-lg text-gray-700 dark:text-gray-300 mb-6">
                In 2026, standard tooling like Lighthouse and Chrome DevTools includes "Carbon Weight". 
                <br/>
                <strong>Green Score:</strong> A (Less than 0.5g CO2 per visit) to F (More than 2g CO2).
            </p>
            <div class="bg-gray-100 dark:bg-slate-900 p-6 rounded-xl border border-gray-200 dark:border-slate-800 font-mono text-xs md:text-sm">
                <div>// Lighthouse 12.0 Output</div>
                <div class="flex items-center gap-4 mt-2">
                    <span class="text-emerald-500 font-bold">Performance: 98</span>
                    <span class="text-emerald-500 font-bold">Accessibility: 100</span>
                    <span class="text-emerald-500 font-bold">Sustainability: 94 🌿</span>
                </div>
            </div>
        </section>
        
        <!-- 08. Green Hosting -->
        <section id="green-hosting" class="scroll-mt-32">
             <h2 class="text-3xl md:text-4xl font-extrabold text-gray-900 dark:text-white mb-8 flex items-center gap-4 border-b pb-4 dark:border-gray-800">
                <span class="text-emerald-600 dark:text-emerald-500">08.</span>
                Green Hosting Strategy
            </h2>
            <p class="text-lg text-gray-700 dark:text-gray-300 mb-6">
                Where you deploy matters. Some cloud regions run on coal. Some run on wind and hydro.
            </p>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div class="border border-green-500 dark:border-green-600 bg-green-50 dark:bg-green-900/10 p-4 rounded-lg">
                    <strong class="text-green-700 dark:text-green-400 block mb-2">✅ Good Regions</strong>
                    <ul class="text-sm space-y-1">
                        <li>AWS us-west-2 (Oregon) - Hydro</li>
                        <li>GCP europe-north1 (Finland) - Wind</li>
                        <li>Azure norway-east - Hydropower</li>
                    </ul>
                </div>
                 <div class="border border-red-500 dark:border-red-600 bg-red-50 dark:bg-red-900/10 p-4 rounded-lg">
                    <strong class="text-red-700 dark:text-red-400 block mb-2">❌ Dirty Regions</strong>
                    <ul class="text-sm space-y-1">
                        <li>Regions heavily reliant on coal grids without offsets.</li>
                        <li>Avoid us-east-1 (Virginia) if possible (Mixed grid).</li>
                    </ul>
                </div>
            </div>
        </section>

        <!-- 09. Carbon Calculator Hook -->
        <section id="carbon-calculator-hook" class="scroll-mt-32">
             <h2 class="text-3xl md:text-4xl font-extrabold text-gray-900 dark:text-white mb-8 flex items-center gap-4 border-b pb-4 dark:border-gray-800">
                <span class="text-emerald-600 dark:text-emerald-500">09.</span>
                Build: useCarbonFootprint
            </h2>
            <p class="text-lg text-gray-700 dark:text-gray-300 mb-8">
                Let's build a hook that estimates the session's carbon impact based on live data transfer metrics. This component helps users understand the "weight" of their browsing session.
            </p>
        </section>

        <!-- 10. Share -->
        <section id="virality" class="scroll-mt-32 pt-12 border-t border-gray-200 dark:border-gray-800">
             <h2 class="text-3xl md:text-4xl font-extrabold text-gray-900 dark:text-white mb-8">
                10. Join the Green Web
            </h2>
            <div class="bg-emerald-600 text-white p-8 rounded-2xl mb-8 shadow-xl">
                 <p class="text-xl font-bold mb-4 !text-white">"We do not inherit the web from our ancestors; we borrow it from our children."</p>
                 <p className="text-emerald-100">
                     Start measuring. Start optimizing. Start thinning your bundles. The future of React is Green.
                 </p>
            </div>
        </section>
    </div>
    `,
    code: `import React, { useState, useEffect } from 'react';
import { Leaf, Info } from 'lucide-react';

// 🌿 Sustainable Component: Carbon Footprint Calculator
// Estimates CO2 based on transferred data (Network API)

const CARBON_PER_GB = 0.11; // kgCO2 per GB (Global Average approximation)

export default function CarbonAwareBadge() {
  const [dataTransferred, setDataTransferred] = useState(0); // in MB
  const [co2, setCo2] = useState(0); // in grams

  useEffect(() => {
    // 1. Check for Performance API support
    if (window.performance && window.performance.getEntriesByType) {
      const calculate = () => {
        const resources = window.performance.getEntriesByType("resource");
        let totalBytes = resources.reduce((acc, res) => acc + (res.transferSize || 0), 0);
        // Add navigation transfer (HTML doc)
        const nav = window.performance.getEntriesByType("navigation")[0];
        if (nav) totalBytes += (nav.transferSize || 0);

        const mb = totalBytes / (1024 * 1024);
        const gb = totalBytes / (1024 * 1024 * 1024);
        
        setDataTransferred(mb.toFixed(2));
        setCo2((gb * CARBON_PER_GB * 1000).toFixed(3)); // Convert kg to g
      };

      // Calculate on load & setup observer for new requests
      calculate();
      
      const observer = new PerformanceObserver((list) => {
          calculate();
      });
      observer.observe({ entryTypes: ['resource'] });

      return () => observer.disconnect();
    }
  }, []);

  const getRating = (val) => {
      if (val < 0.2) return { label: 'Excellent', color: 'bg-emerald-500' };
      if (val < 0.5) return { label: 'Good', color: 'bg-yellow-500' };
      return { label: 'Heavy', color: 'bg-red-500' };
  };

  const rating = getRating(Number(co2));

  return (
    <div className="bg-white dark:bg-slate-900 border border-emerald-100 dark:border-emerald-900/30 rounded-full p-1 pr-4 inline-flex items-center gap-3 shadow-sm hover:shadow-md transition-shadow">
      <div className={\`p-2 rounded-full \${rating.color} text-white\`}>
        <Leaf size={16} fill="currentColor" />
      </div>
      <div>
        <div className="text-[10px] uppercase font-bold text-gray-400 tracking-wider">Session Impact</div>
        <div className="text-sm font-bold text-gray-800 dark:text-gray-200 tabular-nums">
           {co2}g CO₂ <span className="text-gray-400 font-normal">({dataTransferred} MB)</span>
        </div>
      </div>
      <div className="hidden md:block pl-2 border-l border-gray-100 dark:border-gray-800">
         <span className={\`text-xs font-bold px-2 py-0.5 rounded-md \${rating.color} bg-opacity-10 text-opacity-100 \${rating.color.replace('bg-', 'text-')}\`}>
             {rating.label}
         </span>
      </div>
    </div>
  );
}
`
};
